### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by kitovoi111** [snackbag/TT20#10]
[crash-2024-07-22_08.31.12-server.txt](https://github.com/user-attachments/files/16328295/crash-2024-07-22_08.31.12-server.txt)
[latest.log](https://github.com/user-attachments/files/16328296/latest.log)

**Comment by Dreeam-qwq** [comment]
duplicate with https://github.com/snackbag/TT20/issues/5

set `fluid-acceleration` to false in `config/tt20/config.json`

**Comment by JXSnack** [comment]
as Dreeam-qwq said

**Comment by JXSnack** [comment]
Fixed in release 0.7.0 along with some other nice features! You can download it on [Modrinth](https://modrinth.com/mod/tt20)

**Comment by kitovoi111** [comment]
> Fixed in release 0.7.0 along with some other nice features! You can download it on [Modrinth](https://modrinth.com/mod/tt20)

please forge 1.19.2
