### ISSUE TITLE
Concurrent Modification Exception

### ISSUE THREAD

**Issue by KianBrose** [snackbag/TT20#15]
It seems that TT20 does not play well together with chunky. A bug was found where the server would occasionally crash during chunky generations due to a ConcurrentModificationException as seen in the log below:

![image](https://github.com/user-attachments/assets/fb5f284c-9d49-49df-b1d4-857a56e602ac)

**Comment by JXSnack** [comment]
What version of TT20 are you using?

**Comment by KianBrose** [comment]
It was 0.6.0

**Comment by JXSnack** [comment]
Try on [0.7.0](https://modrinth.com/mod/tt20), it should be fixed
