### ISSUE TITLE
fluid acceleration break some mechanisms

### ISSUE THREAD

**Issue by Rozbiynk** [snackbag/TT20#17]
Mod version: 0.7.0
Mc version: 1.21
How to reproduce: 
1. Download and paste DaveRooney's Cobble farm https://cdn.discordapp.com/attachments/1155563105787592784/1156256154960265227/DaveRooneysCobblestoneFarmV1.litematic?ex=66d7d8b5&is=66d68735&hm=25ba441f2e10610e27ec2aa413b5c30fa10f8ba72bd65c5e89692f9ec90c95ab& 
https://www.youtube.com/watch?v=WvzDN2uuLpE
2. Run it few minutes. You notice that clock will break. If you change clock it will produce extra blocks on some lines
Same problems with many moss farms, it just start generating cobblestone and break farm

**Comment by ElapsingDreams** [comment]
when i change {"fluid-acceleration": true} it to false , it cause my server crush
i use tt20-0.7.0+mc1.21.jar
and all mods here:

![image](https://github.com/user-attachments/assets/c56e4248-7510-4666-b74a-3d125f794fcc)
