### ISSUE TITLE
Crash on feature generation (ConcurrentModificationException)

### ISSUE THREAD

**Issue by Legendmanj** [snackbag/TT20#5]
TT20 mod crashes due to the `ConcurrentModificationException`

please mind fixing it 

https://mclo.gs/G6H7GC9
the crash log

**Comment by JXSnack** [comment]
Hey! This seems to be a bug with fluid acceleration -- for now just disable fluid acceleration in the config (located in `config/tt20/config.json`, under the key `fluid-acceleration` (set it to false)

As a separate question: did this error occur on singleplayer or multiplayer?

**Comment by Legendmanj** [comment]
> Hey! This seems to be a bug with fluid acceleration -- for now just disable fluid acceleration in the config (located in `config/tt20/config.json`, under the key `fluid-acceleration` (set it to false)
> 
> As a separate question: did this error occur on singleplayer or multiplayer?

multiplayer

**Comment by Legendmanj** [comment]
> Hey! This seems to be a bug with fluid acceleration -- for now just disable fluid acceleration in the config (located in `config/tt20/config.json`, under the key `fluid-acceleration` (set it to false)
> 
> As a separate question: did this error occur on singleplayer or multiplayer?

hey! it seems that you release a new version a day ago, would using that version fix my issue? can i set fluid acceleration back to true as i have uploaded the new version to the server.
thanks for your previous help mate!

**Comment by JXSnack** [comment]
Huh? I did not upload a new version for TT20, I just uploaded a 1.19.2 port

**Comment by Legendmanj** [comment]
> Huh? I did not upload a new version for TT20, I just uploaded a 1.19.2 port

lmao nvm, i saw the new uploaded 2 days ago and thought u released a new version. ggs
so about the fluid acceleration! do i have to wait for you to upload a new release or is there any i can do to not crash?

**Comment by yizexiaomu** [comment]
My server has also encountered the same issue, so when can the author fix it

**Comment by JXSnack** [comment]
Fixed in release 0.7.0 along with some other nice features! You can download it on [Modrinth](https://modrinth.com/mod/tt20)
